### ISSUE TITLE
A perceptible delay for onPinchEnd to onActionEnd

### ISSUE THREAD

**Issue by YuHsingWu** [cardinalblue/collage-gesture-detector-android#7]
There would be a perceptible delay between onPinchEnd to onActionEnd.
So if I refresh view on onActionEnd after pinch, that would be a about 150ms delay.

05-18 17:25:43.533 13795-13795/com.cardinalblue.demo I/System.out: 🔍 onPinchEnd
05-18 17:25:43.691 13795-13795/com.cardinalblue.demo I/System.out: ⬆onActionEnd

**Comment by tcw165** [comment]
Solved in this commit, https://github.com/cardinalblue/collage-gesture-detector-android/commit/c113c1f215656c879448c573626d3192296a3c9c
